/* Plugins. */
import { StyleSheet } from "react-native";

export function createStyles(isDark) {
    return StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: !isDark ? "#F8F9FA" : '#171D37',
        },
        headerSection: {
            backgroundColor: '#FF4D67',
            borderBottomLeftRadius: 40,
            borderBottomRightRadius: 40,
            paddingTop: 50,
            paddingBottom: 25,
            paddingHorizontal: 20,
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center'
        },
        headerTitle: {
            fontSize: 20,
            fontWeight: '600',
            color: '#fff',
            fontFamily: 'Lexend_400Regular',
        },
        navButton: {
            width: 40,
            height: 40,
            justifyContent: 'center',
            alignItems: 'center',
        },
        headerIconContainer: {
            alignItems: 'center',
            marginTop: 10,
        },
        scrollViewContainer: {
            backgroundColor: !isDark ? "#F8F9FA" : '#171D37',
            flex: 1
        },
        content: {
            padding: 20,
            paddingBottom: 40,
        },
        introSection: {
            marginBottom: 30,
        },
        bannerImage: {
            width: '100%',
            height: 180,
            borderRadius: 16,
            marginBottom: 15,
            backgroundColor: '#E0E0E0',
        },
        lastUpdated: {
            fontSize: 12,
            color: '#999',
            marginBottom: 10,
            fontFamily: 'Lexend_400Regular',
        },
        introText: {
            fontSize: 15,
            color: !isDark ? "#666" : '#c3bebeff',
            lineHeight: 24,
            textAlign: 'justify',
            fontFamily: 'Lexend_400Regular',
        },
        section: {
            marginBottom: 30,
        },
        sectionHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            marginBottom: 15,
        },
        sectionTitle: {
            fontSize: 18,
            fontWeight: '600',
            color: !isDark ? "#333" : '#fdfdfdff',
            marginLeft: 10,
            fontFamily: 'Lexend_400Regular',
        },
        subsection: {
            marginBottom: 20,
        },
        subsectionTitle: {
            fontSize: 16,
            fontWeight: '600',
            color: !isDark ? "#333" : '#a19e9eff',
            marginBottom: 10,
            fontFamily: 'Lexend_400Regular',
        },
        bodyText: {
            fontSize: 14,
            color: !isDark ? "#666" : '#c3bebeff',
            lineHeight: 22,
            marginBottom: 15,
            fontFamily: 'Lexend_400Regular',
        },
        bulletPoint: {
            flexDirection: 'row',
            alignItems: 'center',
            marginBottom: 8,
            paddingLeft: 10,
        },
        bulletText: {
            fontSize: 14,
            color: !isDark ? "#666" : '#c3bebeff',
            marginLeft: 10,
            flex: 1,
            fontFamily: 'Lexend_400Regular',
        },
        contentImage: {
            width: '100%',
            height: 150,
            borderRadius: 12,
            marginTop: 15,
            backgroundColor: '#E0E0E0',
        },
        card: {
            flexDirection: 'row',
            backgroundColor: !isDark ? "#fff" : '#171D37',
            shadowColor: !isDark ? '#000' : "#fff",
            borderRadius: 12,
            padding: 15,
            marginBottom: 12,
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            elevation: 3,
        },
        cardIcon: {
            width: 40,
            height: 40,
            borderRadius: 20,
            backgroundColor: '#FFE5EA',
            alignItems: 'center',
            justifyContent: 'center',
            marginRight: 15,
        },
        cardContent: {
            flex: 1,
        },
        cardTitle: {
            fontSize: 15,
            fontWeight: '600',
            color: !isDark ? "#666" : '#fdfdfdff',
            marginBottom: 5,
            fontFamily: 'Lexend_400Regular',
        },
        cardText: {
            fontSize: 13,
            color: !isDark ? "#666" : '#c3bebeff',
            lineHeight: 20,
            fontFamily: 'Lexend_400Regular',
        },
        securityGrid: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            justifyContent: 'space-between',
            marginTop: 15,
        },
        securityItem: {
            width: '48%',
            backgroundColor: !isDark ? "#fff" : '#171D37',
            shadowColor: !isDark ? '#000' : "#fff",
            borderRadius: 12,
            padding: 20,
            alignItems: 'center',
            marginBottom: 12,
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            elevation: 3,
        },
        securityText: {
            fontSize: 13,
            color: !isDark ? "#666" : '#c3bebeff',
            marginTop: 10,
            textAlign: 'center',
            fontFamily: 'Lexend_400Regular',
        },
        highlightBox: {
            backgroundColor: '#FFF5F7',
            borderRadius: 12,
            padding: 15,
            borderLeftWidth: 4,
            borderLeftColor: '#FF4D67',
            marginTop: 10,
        },
        rightsContainer: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            justifyContent: 'space-between',
            marginTop: 15,
        },
        rightItem: {
            width: '48%',
            backgroundColor: !isDark ? "#fff" : '#171D37',
            shadowColor: !isDark ? '#000' : "#fff",
            borderRadius: 12,
            padding: 15,
            alignItems: 'center',
            marginBottom: 12,
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            elevation: 3,
        },
        rightIconContainer: {
            width: 50,
            height: 50,
            borderRadius: 25,
            backgroundColor: '#FF4D67',
            alignItems: 'center',
            justifyContent: 'center',
            marginBottom: 10,
        },
        rightTitle: {
            fontSize: 14,
            fontWeight: '600',
            color: !isDark ? "#666" : '#e4e3e3ff',
            marginBottom: 5,
            textAlign: 'center',
            fontFamily: 'Lexend_400Regular',
        },
        rightText: {
            fontSize: 12,
            color: !isDark ? "#666" : '#c3bebeff',
            textAlign: 'center',
            fontFamily: 'Lexend_400Regular',
        },
        contactSection: {
            backgroundColor: '#fff',
            borderRadius: 16,
            padding: 20,
            marginTop: 10,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            elevation: 3,
        },
        contactTitle: {
            fontSize: 18,
            fontWeight: '600',
            color: '#333',
            marginBottom: 10,
            textAlign: 'center',
            fontFamily: 'Lexend_400Regular',
        },
        contactText: {
            fontSize: 14,
            color: '#666',
            marginBottom: 15,
            textAlign: 'center',
            fontFamily: 'Lexend_400Regular',
        },
        contactItem: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingVertical: 10,
            borderBottomWidth: 1,
            borderBottomColor: '#F0F0F0',
        },
        contactItemText: {
            fontSize: 14,
            color: '#333',
            marginLeft: 15,
            fontFamily: 'Lexend_400Regular',
        },
        footerImageContainer: {
            alignItems: 'center',
            marginTop: 20,
        },
        footerImage: {
            width: '100%',
            height: 120,
            borderRadius: 12,
            backgroundColor: '#E0E0E0',
        }
    })
};