/* Plugins. */
import { StyleSheet } from "react-native";

export function createStyles(isDark) {
    return StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: !isDark ? "#F5F5F5" : "#171D37",
        },
        headerSection: {
            backgroundColor: '#FF4D67',
            borderBottomLeftRadius: 20,
            borderBottomRightRadius: 20,
            paddingTop: 50,
            paddingBottom: 5,
            paddingHorizontal: 20,
        },
        scrollView: {
            flex: 1,
            borderTopLeftRadius: 12,
            paddingTop: 20
        },
        topNav: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: 20,
        },
        navButton: {
            width: 40,
            height: 40,
            justifyContent: 'center',
            alignItems: 'center',
        },
        headerTitle: {
            fontSize: 20,
            fontWeight: '600',
            color: '#fff',
            fontFamily: 'Lexend_400Regular',
        },
        headerIconContainer: {
            alignItems: 'center',
            marginTop: 10,
        },
        iconCircle: {
            width: 80,
            height: 80,
            borderRadius: 40,
            backgroundColor: 'rgba(255, 255, 255, 0.2)',
            alignItems: 'center',
            justifyContent: 'center',
            borderWidth: 3,
            borderColor: '#fff',
        },
        content: {
            marginTop: 20,
            padding: 20,
            paddingBottom: 40,
        },
        logoContainer: {
            marginBottom: 25
        },
        appLogo: {
            width: 80,
            height: 80,
            borderRadius: 20,
        },
        section: {
            marginBottom: 30,
        },
        sectionTitle: {
            fontSize: 20,
            fontWeight: '600',
            color: '#333',
            marginBottom: 15,
            fontFamily: 'Lexend_400Regular',
        },
        sectionText: {
            fontSize: 15,
            color: '#666',
            lineHeight: 24,
            textAlign: 'justify',
            fontFamily: 'Lexend_400Regular',
        },
        featureCard: {
            backgroundColor: '#fff',
            borderRadius: 16,
            marginBottom: 15,
            overflow: 'hidden',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            elevation: 3,
        },
        featureImage: {
            width: '100%',
            height: 150,
            backgroundColor: '#E0E0E0',
        },
        featureContent: {
            padding: 20,
        },
        featureIconContainer: {
            marginBottom: 10,
        },
        featureTitle: {
            fontSize: 16,
            fontWeight: '600',
            color: '#333',
            marginBottom: 8,
            fontFamily: 'Lexend_400Regular',
        },
        featureText: {
            fontSize: 14,
            color: '#666',
            lineHeight: 20,
            fontFamily: 'Lexend_400Regular',
        },
        teamContainer: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            flexWrap: 'wrap',
        },
        teamMember: {
            alignItems: 'center',
            width: '30%',
            marginBottom: 20,
        },
        teamImage: {
            width: 80,
            height: 80,
            borderRadius: 40,
            backgroundColor: '#E0E0E0',
            marginBottom: 10,
            borderWidth: 3,
            borderColor: '#FF4D67',
        },
        teamName: {
            fontSize: 14,
            fontWeight: '600',
            color: '#333',
            textAlign: 'center',
            marginBottom: 4,
            fontFamily: 'Lexend_400Regular',
        },
        teamRole: {
            fontSize: 12,
            color: '#666',
            textAlign: 'center',
            fontFamily: 'Lexend_400Regular',
        },
        statsSection: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            marginBottom: 30,
        },
        statCard: {
            flex: 1,
            backgroundColor: '#fff',
            borderRadius: 16,
            padding: 20,
            alignItems: 'center',
            marginHorizontal: 5,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            elevation: 3,
        },
        statNumber: {
            fontSize: 24,
            fontWeight: 'bold',
            color: '#FF4D67',
            marginTop: 10,
            fontFamily: 'Lexend_400Regular',
        },
        statLabel: {
            fontSize: 11,
            color: '#666',
            textAlign: 'center',
            marginTop: 5,
            fontFamily: 'Lexend_400Regular',
        },
        contactItem: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: '#fff',
            padding: 15,
            borderRadius: 12,
            marginBottom: 10,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.05,
            shadowRadius: 3,
            elevation: 2,
        },
        contactText: {
            fontSize: 14,
            color: '#333',
            marginLeft: 15,
            fontFamily: 'Lexend_400Regular',
        },
        socialSection: {
            marginBottom: 30,
            paddingTop: 20,
            borderTopWidth: 1,
            borderTopColor: '#E0E0E0',
        },
        socialContainer: {
            flexDirection: 'row',
            justifyContent: 'flex-start',
            gap: 15,
        },
        socialButton: {
            width: 50,
            height: 50,
            borderRadius: 25,
            backgroundColor: '#FF4D67',
            alignItems: 'center',
            justifyContent: 'center',
            shadowColor: '#FF4D67',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.3,
            shadowRadius: 6,
            elevation: 4,
        },
        versionContainer: {
            alignItems: 'center',

        },
        versionText: {
            fontSize: 12,
            color: '#999',
            marginBottom: 5,
            fontFamily: 'Lexend_400Regular',
        },
        copyrightText: {
            fontSize: 12,
            color: '#999',
            fontFamily: 'Lexend_400Regular',
        },
    })
}