export const COMMON_MODAL_OPEN_START = "COMMON_MODAL_OPEN_START";
export const COMMON_MODAL_OPEN_SUCCESS = "COMMON_MODAL_OPEN_SUCCESS";
export const COMMON_MODAL_OPEN_ERROR= "COMMON_MODAL_OPEN_ERROR";

export const COMMON_MODAL_CLOSE_START = "COMMON_MODAL_CLOSE_START";
export const COMMON_MODAL_CLOSE_SUCCESS = "COMMON_MODAL_CLOSE_SUCCESS";
export const COMMON_MODAL_CLOSE_ERROR = "COMMON_MODAL_CLOSE_ERROR";