/* Plugins. */
import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get('window');
const CARD_WIDTH = (width - 48) / 2;

export function createStyles(isDark) {
    return StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: isDark ? "#171D37" : "#f8f9fa"
        },
        searchContainer: {
            paddingHorizontal: 16,
            paddingVertical: 16,
        },
        searchInputWrapper: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: isDark ? "#171D37" : "#f8f9fa",
            borderRadius: 12,
            paddingHorizontal: 16,
            paddingVertical: 12,
            borderWidth: 1,
            borderColor: isDark ? '#4a4a4a' : '#e5e5e5',
        },
        searchIcon: {
            marginRight: 10,
        },
        searchInput: {
            flex: 1,
            fontSize: 15,
            color: isDark ? '#fff' : '#333',
            fontFamily: 'Lexend_400Regular',
            padding: 0,
        },
        clearButton: {
            padding: 4,
        },
        header: {
            backgroundColor: isDark ? '#2a2a2a' : '#fff',
            padding: 20,
            paddingTop: 60,
            borderBottomWidth: 1,
            borderBottomColor: isDark ? '#3a3a3a' : '#f0f0f0',
        },
        headerTitle: {
            fontSize: 28,
            fontWeight: 'bold',
            color: isDark ? '#fff' : '#333',
            marginBottom: 4,
            fontFamily: 'Lexend_700Bold',
        },
        headerSubtitle: {
            fontSize: 14,
            color: isDark ? '#999' : '#666',
            fontFamily: 'Lexend_400Regular',
        },
        loadingContainer: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
        },
        loadingText: {
            marginTop: 12,
            fontSize: 16,
            color: isDark ? '#999' : '#666',
            fontFamily: 'Lexend_400Regular',
        },
        emptyContainer: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            padding: 40,
        },
        emptyText: {
            fontSize: 20,
            fontWeight: 'bold',
            color: isDark ? '#fff' : '#333',
            marginTop: 16,
            fontFamily: 'Lexend_400Regular',
        },
        emptySubtext: {
            fontSize: 14,
            color: isDark ? '#999' : '#666',
            marginTop: 8,
            textAlign: 'center',
            fontFamily: 'Lexend_400Regular',
        },
        habitsList: {
            flex: 1,
        },
        habitsListContent: {
            padding: 16,
            flexDirection: 'row',
            flexWrap: 'wrap',
            justifyContent: 'space-between',
        },
        habitCardWrapper: {
            width: CARD_WIDTH,
            marginBottom: 16,
        },
        habitCard: {
            width: '100%',
            backgroundColor: isDark ? "#171D37" : "#f8f9fa",
            borderRadius: 16,
            shadowColor: !isDark ? "#000" : "#fff",
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 8,
            elevation: 3,
            overflow: 'hidden',
        },
        habitImageContainer: {
            position: 'relative',
            height: 140,
            width: '100%',
        },
        habitImage: {
            width: '100%',
            height: '100%',
        },
        habitImagePlaceholder: {
            width: '100%',
            height: '100%',
            backgroundColor: isDark ? '#3a3a3a' : '#f0f0f0',
            justifyContent: 'center',
            alignItems: 'center',
        },
        lifestyleBadge: {
            position: 'absolute',
            top: 8,
            left: 8,
            backgroundColor: '#FF4D67',
            paddingHorizontal: 10,
            paddingVertical: 4,
            borderRadius: 12,
        },
        lifestyleBadgeText: {
            color: '#fff',
            fontSize: 10,
            fontWeight: '600',
            textTransform: 'capitalize',
            fontFamily: 'Lexend_400Regular',
        },
        deleteButtonOnImage: {
            position: 'absolute',
            top: 8,
            right: 8,
            backgroundColor: 'rgba(255, 77, 103, 0.9)',
            width: 32,
            height: 32,
            borderRadius: 16,
            justifyContent: 'center',
            alignItems: 'center',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.2,
            shadowRadius: 4,
            elevation: 4,
        },
        habitInfo: {
            padding: 12,
        },
        habitHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'flex-start',
            marginBottom: 6,
        },
        habitName: {
            fontSize: 16,
            fontWeight: '600',
            color: isDark ? '#fff' : '#333',
            flex: 1,
            fontFamily: 'Lexend_500Medium',
        },
        habitDescription: {
            fontSize: 12,
            color: isDark ? '#999' : '#666',
            marginBottom: 10,
            lineHeight: 16,
            fontFamily: 'Lexend_400Regular',
        },
        habitFooter: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
        },
        timeContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 4,
        },
        timeText: {
            fontSize: 11,
            color: isDark ? '#999' : '#666',
            fontFamily: 'Lexend_400Regular',
        },
        imagesCount: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 4,
        },
        imagesCountText: {
            fontSize: 11,
            color: isDark ? '#999' : '#666',
            fontFamily: 'Lexend_400Regular',
        },
        addButton: {
            position: 'absolute',
            bottom: 30,
            right: 30,
            width: 50,
            height: 50,
            borderRadius: 30,
            backgroundColor: '#FF4D67',
            justifyContent: 'center',
            alignItems: 'center',
            shadowColor: '#FF4D67',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.3,
            shadowRadius: 8,
            elevation: 10,
            zIndex: 2
        },
        modalOverlay: {
            flex: 1,
            backgroundColor: 'rgba(0, 0, 0, 0.5)',
            justifyContent: 'flex-end',
        },
        modalContent: {
            backgroundColor: isDark ? "#171D37" : "#f8f9fa",
            borderTopLeftRadius: 24,
            borderTopRightRadius: 24,
            maxHeight: '90%',
            paddingBottom: 20,
        },
        modalHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            padding: 20,
            borderBottomWidth: 1,
            borderBottomColor: isDark ? '#3a3a3a' : '#f0f0f0',
        },
        modalTitle: {
            fontSize: 22,
            color: isDark ? '#fff' : '#333',
            fontFamily: 'Lexend_500Medium',
        },
        modalBody: {
            paddingHorizontal: 20,
        },
        label: {
            fontSize: 16,
            color: isDark ? '#fff' : '#333',
            marginBottom: 8,
            marginTop: 16,
            fontFamily: 'Lexend_400Regular',
        },
        imageScroll: {
            marginBottom: 8,
        },
        imagePreviewContainer: {
            position: 'relative',
            marginRight: 12,
            fontFamily: 'Lexend_400Regular',
        },
        imagePreview: {
            width: 100,
            height: 100,
            borderRadius: 12,
        },
        removeImageButton: {
            position: 'absolute',
            top: 4,
            right: 4,
            backgroundColor: '#FF4D67',
            borderRadius: 12,
            width: 24,
            height: 24,
            justifyContent: 'center',
            alignItems: 'center',
        },
        thumbnailButton: {
            position: 'absolute',
            bottom: 4,
            right: 4,
            backgroundColor: 'rgba(0, 0, 0, 0.5)',
            borderRadius: 12,
            width: 24,
            height: 24,
            justifyContent: 'center',
            alignItems: 'center',
        },
        thumbnailButtonActive: {
            backgroundColor: '#FF4D67',
        },
        thumbnailBadge: {
            position: 'absolute',
            bottom: 4,
            left: 4,
            backgroundColor: '#FF4D67',
            paddingHorizontal: 8,
            paddingVertical: 3,
            borderRadius: 8,
        },
        thumbnailText: {
            color: '#fff',
            fontSize: 10,
            fontWeight: '600',
        },
        addImageButton: {
            width: 100,
            height: 100,
            borderRadius: 12,
            borderWidth: 2,
            borderColor: '#FF4D67',
            borderStyle: 'dashed',
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: isDark ? "#171D37" : "#f8f9fa",
        },
        addImageText: {
            marginTop: 4,
            fontSize: 12,
            color: '#FF4D67',
            fontWeight: '600',
        },
        input: {
            backgroundColor: isDark ? "#171D37" : "#f8f9fa",
            borderRadius: 12,
            padding: 14,
            fontSize: 15,
            color: isDark ? '#fff' : '#333',
            borderWidth: 1,
            borderColor: isDark ? '#4a4a4a' : '#e0e0e0',
            fontFamily: 'Lexend_400Regular',
        },
        inputError: {
            borderColor: '#FF4D67',
        },
        textArea: {
            height: 80,
            textAlignVertical: 'top',
        },
        errorText: {
            color: '#FF4D67',
            fontSize: 12,
            marginTop: 4,
            marginLeft: 4,
        },
        radioGroup: {
            gap: 12,
        },
        radioOption: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingVertical: 8,
        },
        radioCircle: {
            width: 22,
            height: 22,
            borderRadius: 11,
            borderWidth: 2,
            borderColor: isDark ? '#666' : '#ccc',
            justifyContent: 'center',
            alignItems: 'center',
            marginRight: 12,
        },
        radioCircleSelected: {
            borderColor: '#FF4D67',
        },
        radioInner: {
            width: 12,
            height: 12,
            borderRadius: 6,
            backgroundColor: '#FF4D67',
        },
        radioLabel: {
            fontSize: 15,
            color: isDark ? '#fff' : '#333',
            textTransform: 'capitalize',
            fontFamily: 'Lexend_400Regular',
        },
        saveButton: {
            backgroundColor: '#FF4D67',
            margin: 20,
            marginTop: 10,
            paddingVertical: 16,
            borderRadius: 12,
            alignItems: 'center',
            shadowColor: '#FF4D67',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.3,
            shadowRadius: 8,
            elevation: 4,
        },
        saveButtonDisabled: {
            opacity: 0.7,
        },
        saveButtonText: {
            color: '#fff',
            fontSize: 16,
            fontWeight: '600',
            fontFamily: 'Lexend_400Regular',
        },
        pickerOverlay: {
            flex: 1,
            backgroundColor: 'rgba(0, 0, 0, 0.5)',
            justifyContent: 'center',
            alignItems: 'center',
            padding: 20,
        },
        pickerContainer: {
            backgroundColor: isDark ? '#2a2a2a' : '#fff',
            borderRadius: 16,
            width: '100%',
            maxWidth: 400,
            overflow: 'hidden',
        },
        pickerOption: {
            flexDirection: 'row',
            alignItems: 'center',
            padding: 20,
            gap: 16,
        },
        pickerOptionText: {
            fontSize: 16,
            color: isDark ? '#fff' : '#333',
            fontWeight: '600',
        },
        pickerDivider: {
            height: 1,
            backgroundColor: isDark ? '#3a3a3a' : '#f0f0f0',
        },
    });
}